Food_Online/Controllers/AuthenticationController.cs
using Food_Online.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Food_Online.Controllers
{
    public class AuthenticationController : Controller
    {
        // GET: Authentication
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DoLogin(UserDetails u)
        {
            Customer bal = new Customer();
            if (bal.IsValidUser(u))
            {
                FormsAuthentication.SetAuthCookie(u.UserName, false);
                return RedirectToAction("Index", "Foods");
            }
            else
            {
                ModelState.AddModelError("CredentialError", "Invalid Username or Password");
                return View("Login");
            }
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

Food_Online/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Food_Online.Models;

namespace Food_Online.Controllers
{
    public class CategoriesController : Controller
    {
        private FoodOnline_ModelContainer db = new FoodOnline_ModelContainer();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.CategorySet.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            if (User.Identity.Name != "")
            {
                Customer c = db.CustomerSet.FirstOrDefault(u => u.Username == User.Identity.Name);
                ViewData["User"] = c;
            }
            ViewData["category"] = db.CategorySet.Find(id);
            return View();
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.CategorySet.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.CategorySet.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.CategorySet.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.CategorySet.Find(id);
            db.CategorySet.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Food_Online/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Food_Online.Models;

namespace Food_Online.Controllers
{
    public class CustomersController : Controller
    {
        private FoodOnline_ModelContainer db = new FoodOnline_ModelContainer();

        // GET: Customers
        public ActionResult Index()
        {
            return View(db.CustomerSet.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details()
        {
            if (User.Identity.Name != "")
            {
                Customer customer = db.CustomerSet.FirstOrDefault(u => u.Username == User.Identity.Name);
                return View(customer);
            }
            else
            {
                return HttpNotFound();
            }
            
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Username,Password,ConfirmPassword,Fname,Lname,Address,Email,Phone_num")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                if (customer.IsUsernameExist())
                {
                    if (customer.IsEmailExist())
                    {
                        db.CustomerSet.Add(customer);
                        db.SaveChanges();
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Email already exist");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Username already exist");
                }
                
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.CustomerSet.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Username,Password,ConfirmPassword,Fname,Lname,Address,Email,Phone_num")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.CustomerSet.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.CustomerSet.Find(id);
            db.CustomerSet.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Food_Online/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @{ 
        Food_Online.Models.FoodOnline_ModelContainer DB = new Food_Online.Models.FoodOnline_ModelContainer();
        var navbar_categories = DB.CategorySet.ToList();
    }
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" >
            <div class="navbar-header" >
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/Home/Index" class="navbar-brand"><img src="https://www.picz.in.th/images/2017/12/15/buwinrestarant.png" width="100"></a>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="navbar-brand" style="font-size:24px;">@Html.ActionLink("Menu", "Index", "Foods")</li>
                    <li  class="navbar-brand" style="font-size:24px;">@Html.ActionLink("Cart", "Index", "Orders")</li>
                    <li class="dropdown  navbar-brand">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="font-size:24px;">Category<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            @foreach (var c in navbar_categories)
                            {
                                <li style="font-size: 16px;">
                                    @Html.ActionLink(c.Name, "Details" ,"Categories" , new { id=c.Id },null)
                                </li>
                            }
                        </ul>
                    </li>
                   
                </ul>
                    
                    @{
                        if (User.Identity.Name != "")
                        {
                            <ul class="nav navbar-nav navbar-right">
                                <li class="navbar-brand" style="font-size:24px;">@Html.ActionLink("Welcome " + User.Identity.Name, "Details" , "Customers" , null ,null)</li>
                                <li class="navbar-brand" style="font-size:24px;">@Html.ActionLink("Logout", "Logout", "Authentication")</li>
                            </ul>
                        }
                        else
                        {
                            <ul class="nav navbar-nav navbar-right">
                                <li class="navbar-brand" style="font-size:24px;">@Html.ActionLink("Login", "Login", "Authentication", null,null)</li>
                            </ul>
                        }
                    }
                           
            </div>
        </div>
    </div>
    <div class="container body-content">
     @RenderBody()
    <hr />
    <footer>
        <p>
            Contact: 088-4342419<br>
            Email: kasididh_raumsook@cmu.ac.th
        </p>

    </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>